// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessages.proto

package org.sharif.ce.firerclient.network;

public final class NetMessages {
  private NetMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NetGpsPointOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional double lat = 1;
    boolean hasLat();
    double getLat();
    
    // optional double lng = 2;
    boolean hasLng();
    double getLng();
    
    // optional double alt = 3;
    boolean hasAlt();
    double getAlt();
    
    // optional string timeTag = 4;
    boolean hasTimeTag();
    String getTimeTag();
    
    // optional int32 wayId = 5;
    boolean hasWayId();
    int getWayId();
  }
  public static final class NetGpsPoint extends
      com.google.protobuf.GeneratedMessageLite
      implements NetGpsPointOrBuilder {
    // Use NetGpsPoint.newBuilder() to construct.
    private NetGpsPoint(Builder builder) {
      super(builder);
    }
    private NetGpsPoint(boolean noInit) {}
    
    private static final NetGpsPoint defaultInstance;
    public static NetGpsPoint getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetGpsPoint getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional double lat = 1;
    public static final int LAT_FIELD_NUMBER = 1;
    private double lat_;
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getLat() {
      return lat_;
    }
    
    // optional double lng = 2;
    public static final int LNG_FIELD_NUMBER = 2;
    private double lng_;
    public boolean hasLng() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getLng() {
      return lng_;
    }
    
    // optional double alt = 3;
    public static final int ALT_FIELD_NUMBER = 3;
    private double alt_;
    public boolean hasAlt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getAlt() {
      return alt_;
    }
    
    // optional string timeTag = 4;
    public static final int TIMETAG_FIELD_NUMBER = 4;
    private java.lang.Object timeTag_;
    public boolean hasTimeTag() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getTimeTag() {
      java.lang.Object ref = timeTag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          timeTag_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeTagBytes() {
      java.lang.Object ref = timeTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        timeTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 wayId = 5;
    public static final int WAYID_FIELD_NUMBER = 5;
    private int wayId_;
    public boolean hasWayId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getWayId() {
      return wayId_;
    }
    
    private void initFields() {
      lat_ = 0D;
      lng_ = 0D;
      alt_ = 0D;
      timeTag_ = "";
      wayId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lng_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, alt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTimeTagBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, wayId_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lng_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, alt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTimeTagBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, wayId_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint, Builder>
        implements org.sharif.ce.firerclient.network.NetMessages.NetGpsPointOrBuilder {
      // Construct using org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        lng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        alt_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        timeTag_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        wayId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint getDefaultInstanceForType() {
        return org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.getDefaultInstance();
      }
      
      public org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint build() {
        org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint buildPartial() {
        org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint result = new org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lng_ = lng_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.alt_ = alt_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timeTag_ = timeTag_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.wayId_ = wayId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint other) {
        if (other == org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.getDefaultInstance()) return this;
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLng()) {
          setLng(other.getLng());
        }
        if (other.hasAlt()) {
          setAlt(other.getAlt());
        }
        if (other.hasTimeTag()) {
          setTimeTag(other.getTimeTag());
        }
        if (other.hasWayId()) {
          setWayId(other.getWayId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              lat_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lng_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              alt_ = input.readDouble();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              timeTag_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              wayId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional double lat = 1;
      private double lat_ ;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getLat() {
        return lat_;
      }
      public Builder setLat(double value) {
        bitField0_ |= 0x00000001;
        lat_ = value;
        
        return this;
      }
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0D;
        
        return this;
      }
      
      // optional double lng = 2;
      private double lng_ ;
      public boolean hasLng() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLng() {
        return lng_;
      }
      public Builder setLng(double value) {
        bitField0_ |= 0x00000002;
        lng_ = value;
        
        return this;
      }
      public Builder clearLng() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lng_ = 0D;
        
        return this;
      }
      
      // optional double alt = 3;
      private double alt_ ;
      public boolean hasAlt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getAlt() {
        return alt_;
      }
      public Builder setAlt(double value) {
        bitField0_ |= 0x00000004;
        alt_ = value;
        
        return this;
      }
      public Builder clearAlt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        alt_ = 0D;
        
        return this;
      }
      
      // optional string timeTag = 4;
      private java.lang.Object timeTag_ = "";
      public boolean hasTimeTag() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTimeTag() {
        java.lang.Object ref = timeTag_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          timeTag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTimeTag(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        timeTag_ = value;
        
        return this;
      }
      public Builder clearTimeTag() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeTag_ = getDefaultInstance().getTimeTag();
        
        return this;
      }
      void setTimeTag(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        timeTag_ = value;
        
      }
      
      // optional int32 wayId = 5;
      private int wayId_ ;
      public boolean hasWayId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getWayId() {
        return wayId_;
      }
      public Builder setWayId(int value) {
        bitField0_ |= 0x00000010;
        wayId_ = value;
        
        return this;
      }
      public Builder clearWayId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        wayId_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:network.NetGpsPoint)
    }
    
    static {
      defaultInstance = new NetGpsPoint(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:network.NetGpsPoint)
  }
  
  public interface NetWayPointOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .network.NetGpsPoint gpsPoints = 1;
    java.util.List<org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint> 
        getGpsPointsList();
    org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint getGpsPoints(int index);
    int getGpsPointsCount();
  }
  public static final class NetWayPoint extends
      com.google.protobuf.GeneratedMessageLite
      implements NetWayPointOrBuilder {
    // Use NetWayPoint.newBuilder() to construct.
    private NetWayPoint(Builder builder) {
      super(builder);
    }
    private NetWayPoint(boolean noInit) {}
    
    private static final NetWayPoint defaultInstance;
    public static NetWayPoint getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetWayPoint getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .network.NetGpsPoint gpsPoints = 1;
    public static final int GPSPOINTS_FIELD_NUMBER = 1;
    private java.util.List<org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint> gpsPoints_;
    public java.util.List<org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint> getGpsPointsList() {
      return gpsPoints_;
    }
    public java.util.List<? extends org.sharif.ce.firerclient.network.NetMessages.NetGpsPointOrBuilder> 
        getGpsPointsOrBuilderList() {
      return gpsPoints_;
    }
    public int getGpsPointsCount() {
      return gpsPoints_.size();
    }
    public org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint getGpsPoints(int index) {
      return gpsPoints_.get(index);
    }
    public org.sharif.ce.firerclient.network.NetMessages.NetGpsPointOrBuilder getGpsPointsOrBuilder(
        int index) {
      return gpsPoints_.get(index);
    }
    
    private void initFields() {
      gpsPoints_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < gpsPoints_.size(); i++) {
        output.writeMessage(1, gpsPoints_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < gpsPoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gpsPoints_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sharif.ce.firerclient.network.NetMessages.NetWayPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sharif.ce.firerclient.network.NetMessages.NetWayPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.sharif.ce.firerclient.network.NetMessages.NetWayPoint, Builder>
        implements org.sharif.ce.firerclient.network.NetMessages.NetWayPointOrBuilder {
      // Construct using org.sharif.ce.firerclient.network.NetMessages.NetWayPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        gpsPoints_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.sharif.ce.firerclient.network.NetMessages.NetWayPoint getDefaultInstanceForType() {
        return org.sharif.ce.firerclient.network.NetMessages.NetWayPoint.getDefaultInstance();
      }
      
      public org.sharif.ce.firerclient.network.NetMessages.NetWayPoint build() {
        org.sharif.ce.firerclient.network.NetMessages.NetWayPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sharif.ce.firerclient.network.NetMessages.NetWayPoint buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sharif.ce.firerclient.network.NetMessages.NetWayPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sharif.ce.firerclient.network.NetMessages.NetWayPoint buildPartial() {
        org.sharif.ce.firerclient.network.NetMessages.NetWayPoint result = new org.sharif.ce.firerclient.network.NetMessages.NetWayPoint(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          gpsPoints_ = java.util.Collections.unmodifiableList(gpsPoints_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.gpsPoints_ = gpsPoints_;
        return result;
      }
      
      public Builder mergeFrom(org.sharif.ce.firerclient.network.NetMessages.NetWayPoint other) {
        if (other == org.sharif.ce.firerclient.network.NetMessages.NetWayPoint.getDefaultInstance()) return this;
        if (!other.gpsPoints_.isEmpty()) {
          if (gpsPoints_.isEmpty()) {
            gpsPoints_ = other.gpsPoints_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGpsPointsIsMutable();
            gpsPoints_.addAll(other.gpsPoints_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.Builder subBuilder = org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGpsPoints(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .network.NetGpsPoint gpsPoints = 1;
      private java.util.List<org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint> gpsPoints_ =
        java.util.Collections.emptyList();
      private void ensureGpsPointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          gpsPoints_ = new java.util.ArrayList<org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint>(gpsPoints_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint> getGpsPointsList() {
        return java.util.Collections.unmodifiableList(gpsPoints_);
      }
      public int getGpsPointsCount() {
        return gpsPoints_.size();
      }
      public org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint getGpsPoints(int index) {
        return gpsPoints_.get(index);
      }
      public Builder setGpsPoints(
          int index, org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGpsPointsIsMutable();
        gpsPoints_.set(index, value);
        
        return this;
      }
      public Builder setGpsPoints(
          int index, org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.Builder builderForValue) {
        ensureGpsPointsIsMutable();
        gpsPoints_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addGpsPoints(org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGpsPointsIsMutable();
        gpsPoints_.add(value);
        
        return this;
      }
      public Builder addGpsPoints(
          int index, org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGpsPointsIsMutable();
        gpsPoints_.add(index, value);
        
        return this;
      }
      public Builder addGpsPoints(
          org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.Builder builderForValue) {
        ensureGpsPointsIsMutable();
        gpsPoints_.add(builderForValue.build());
        
        return this;
      }
      public Builder addGpsPoints(
          int index, org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint.Builder builderForValue) {
        ensureGpsPointsIsMutable();
        gpsPoints_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllGpsPoints(
          java.lang.Iterable<? extends org.sharif.ce.firerclient.network.NetMessages.NetGpsPoint> values) {
        ensureGpsPointsIsMutable();
        super.addAll(values, gpsPoints_);
        
        return this;
      }
      public Builder clearGpsPoints() {
        gpsPoints_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeGpsPoints(int index) {
        ensureGpsPointsIsMutable();
        gpsPoints_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:network.NetWayPoint)
    }
    
    static {
      defaultInstance = new NetWayPoint(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:network.NetWayPoint)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
